name: Publish Release

on:
  push:
    tags:
      - "\\d+\\.\\d+\\.\\d+"

jobs:
  create_release:
    name: Create Release
    runs-on: macos-13
    steps:
      - name: Setup Swift
        uses: swift-actions/setup-swift@v1
        with:
          swift-version: "5.8"

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create XCFramework
        uses: bsneed/swift-create-xcframework@xcode15_fix
        with:
          target: DieKit

      - name: Create GitHub Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            DieKit.sha256
            DieKit.zip
